### ISSUE TITLE
Comments from disqus

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-web-new#12]
Do we have them? If yes, should we restore them? If no, do we want to have comments for the new website?

**Comment by nesquena** [comment]
Would be nice to restore the disqus comments but not critical. @wikimatze do you think we could reconfigure it by reusing these account settings? https://github.com/padrino/padrino-web-classic/blob/55c5db2699cd8557ef0a74b9470d6c715ee1748f/lib/disqus.rb

**Comment by wikimatze** [comment]
Yeah, I did a migration. I'll let you know when I'm done with the other task.

**Comment by wikimatze** [comment]
@padrino/core-members Does anybody has the disqus account information? Please send me a PM!

**Comment by wikimatze** [comment]
I've started the migration with [this csv file](https://gist.github.com/wikimatze/a3facbc2da0da6e64134) => this will take 24 hours. Beside, I started intergating disqus with the [middleman-disqus](https://github.com/simonrice/middleman-disqus) plugin for blog and guides entries. The commands starts appearing (check http://padrinorb.com/guides/).

**Comment by wikimatze** [comment]
Everything what could be migrated is migrated!
