### ISSUE TITLE
Add Google Analytics for Tracking

### ISSUE THREAD

**Issue by nesquena** [padrino/padrino-web-new#15]
We need to add tracking to the page:

http://stackoverflow.com/questions/17207458/how-to-add-google-analytics-tracking-id-to-github-pages

**Comment by wikimatze** [comment]
Okay but we need someone who has the credentials to the account (or create one).

**Comment by wikimatze** [comment]
Does anyone has credentials or should a I create a gmail-account?

**Comment by nesquena** [comment]
@wikimatze Do you have a google account and if so please send me the email? If so I can add you to the analytics page. Same for @angeloashmore

**Comment by nesquena** [comment]
@wikimatze Setup the analytics profile. Tracking id is: UA-72258621-1. Can you try adding to the site? I'll let you know when we start receiving traffic.

**Comment by wikimatze** [comment]
It's lordmatze@gmail.com.

**Comment by wikimatze** [comment]
I have access, thanks.

**Comment by wikimatze** [comment]
I can see in the live-overview, that data is coming in. Before we can close the issue, we need make sure, that the tracking code will not be loaded in `development` environment. Think a simple `if` statement in the `source/layouts/_footer.slim`. Does anybody knows how to do it?

**Comment by angeloashmore** [comment]
@nesquena my Google account is angeloashmore@gmail.com

**Comment by nesquena** [comment]
Great, added!
