### ISSUE TITLE
Middleman 4.0

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-web-new#16]
It's out, so we should update soon.

**Comment by angeloashmore** [comment]
The supporting gems are not 4.0 compatible yet, so let's wait for a bit. It looks like some of the gems are updated on master, but not released.

**Comment by angeloashmore** [comment]
I had to fix the `middleman-search_engine_sitemap` gem to be compatible with Middleman 4. It's pending a PR from the author, but I have our Gemfile pointing to my fork.

Looks like we can close this now! :smile:

**Comment by wikimatze** [comment]
I left a comment on the commit for this - now I got the explanation.
