### ISSUE TITLE
RSS-Feed code-review

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-web-new#19]
Hi there, 

I repaired the RSS-Feed today and add the link in the layout section. The feed is reachable via http://padrinorb.com/feed.xml.

The relevant commits are: https://github.com/padrino/padrino-web-new/compare/fb2f42e...be43b7cd4a

If everything is fine, then I'm happy and will close this issue and will start working in branches for additional features in the future.

**Comment by bascht** [comment]
_bumping-this_

The feed is broken in my news reader since a few weeks now (the old path was `/blog.rss` – it'd be lovely if you could redirect / keep it). :smile_cat: 

Also: The current feed meta data is still referring to `.org`: https://github.com/padrino/padrino-web-new/blob/61c328d4dd7af7ae1651dfa9d1335760e78ad867/source/layouts/_head.slim#L8

**Comment by wikimatze** [comment]
Should be fixed now and the old `/blog.rss` is working now. Didn't find out how to redirect middleman and gh-pages, so the old feed is gone :smile_cat:.

**Comment by bascht** [comment]
Thanks for looking into this! The `/blog.rss` route no longer 404's, but it's also not yet a proper feed:

http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fpadrinorb.com%2Fblog.rss

**Comment by wikimatze** [comment]
Should be valid now!

**Comment by bascht** [comment]
Shines in my feed reader! Thanks for the quick fix! :cake: 

![screenshot-2016-02-19-065256-798x1054](https://cloud.githubusercontent.com/assets/51264/13167650/78ee2fee-d6d5-11e5-943d-96d6551317f0.png)

**Comment by wikimatze** [comment]
Great, by the way, which reader are you using?

**Comment by bascht** [comment]
It's https://miniflux.net.

**Comment by wikimatze** [comment]
Thanks for letting me know!
