### ISSUE TITLE
Capistrano, etc.

### ISSUE THREAD

**Issue by angeloashmore** [padrino/padrino-web-new#21]
@nesquena I noticed a Capistrano setup and a rack file was added to the repo. Is there a need for this?

Middleman generates static HTML files which gets committed directly to the `gh-pages` branch using `middleman-deploy`. Middleman shouldn't be running as server unless in development.

**Comment by nesquena** [comment]
You are completely correct. This was my mistake. I'll revert those changes.

**Comment by nesquena** [comment]
I believe this has all been cleaned up now. Thanks.

**Comment by angeloashmore** [comment]
Awesome, thanks. I'm updating the site to Middleman 4 now so this should help clear things up.

**Comment by nesquena** [comment]
:+1: Great thanks!
