### ISSUE TITLE
Rename this repo to padrino-web

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-web-new#25]
The new is the current one, think we can rename the repository. @padrino/collaborators Please upvote.

**Comment by angeloashmore** [comment]
Does the domain need to be updated if we change the repo name?

**Comment by angeloashmore** [comment]
Sorry, clicked the wrong button. Reopening.

**Comment by wikimatze** [comment]
I don't think that we need to change anything.

**Comment by wikimatze** [comment]
I'll try it out tomorrow and we will see if something gets broken.
