### ISSUE TITLE
Homepage lists latest stable release as 0.13.2

### ISSUE THREAD

**Issue by MatzFan** [padrino/padrino-web-new#34]
I notice your homepage is a couple of releases behind, as you haven't a blogpost on 13.3 or 13.3.1. Can you pick up the GitHub release versions directly, so it is kept up to date?

**Comment by wikimatze** [comment]
See https://github.com/padrino/padrino-docs/commit/db4953d8083ff89fa16fa4ba25863fbb0e97325a for the current number.

**Comment by wikimatze** [comment]
@nesquena can you review the new blog-entry? If it's okay, I'll deploy it. You can see the post on the staging page: http://stagingpadrinorb.wikimatze.de/blog/padrino-0-13-3/

**Comment by nesquena** [comment]
@wikimatze Looks great, thanks so much for putting this together. Go ahead and deploy.

**Comment by wikimatze** [comment]
@MatzFan we are now live with 0.13.3 http://padrinorb.com/blog/padrino-0-13-3/ => The post for 13.3.1 will follow soon.

**Comment by MatzFan** [comment]
awesome - thanks @wikimatze
