### ISSUE TITLE
Guides TOC unordered

### ISSUE THREAD

**Issue by angeloashmore** [padrino/padrino-web-new#37]
The guide TOC is unordered (see the sidebar [here][0]). The layout relies on an ordered Hash, but is a feature of Ruby >=1.9.

@wikimatze Are you running an older version of Ruby on your local system? Or did the changes to `config.rb` remove support for keeping the guides ordered?

[0]: http://padrinorb.com/guides/

**Comment by wikimatze** [comment]
Hi @angeloashmore thanks for taking care of this. I have 

```
ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [i686-linux]
```

running on my machine. I tried to digg into this issue, but couldn't find the issue. When you build the site, do you have the same problems?

**Comment by angeloashmore** [comment]
The guides appear ordered on my machine.

```sh
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

I wonder if this is a difference of macOS and Linux filename handling?

When you go to the Middleman Sitemap, do you see 01_introduction, 02_getting-started, etc. in numerical order?

```ruby
# http://localhost:4567/__middleman/sitemap/

# ...
guides
  01_introduction
  02_getting-started
  03_features
  04_generators
  05_controllers
  06_application-helpers
  07_adding-components
  08_advanced-usage
  adding-components
  advanced-usage
  application-helpers
  controllers
  features
  generators
  getting-started
  introduction
# ...
```

**Comment by wikimatze** [comment]
I'm getting the exact output you get:
![2017-03-20-195534_1920x1200_scrot](https://cloud.githubusercontent.com/assets/264708/24116478/3a80c1ea-0da7-11e7-9ce9-39043a8fc248.png)

**Comment by angeloashmore** [comment]
@wikimatze could you try out the `toc-sort` branch and let me know if it solves the sorting? I just added explicit `#sort_by(&:target)` calls to the places the resources are called.

**Comment by wikimatze** [comment]
Seems much better, if we compare http://stagingpadrinorb.wikimatze.de/guides/ with http://padrinorb.com/guides/. Ready for merge!

**Comment by angeloashmore** [comment]
Thanks, merged!

**Comment by wikimatze** [comment]
Perfect, it's live now. Finally the guides are in the right order.
