### ISSUE TITLE
SSL problems

### ISSUE THREAD

**Issue by jorgefuertes** [padrino/padrino-web-new#38]
Not sure if I should open this issue here, is half a systems problem.

- The cerficate is from github and not valid for padrinorb.com.
- Some resources are loaded with a harcoded schema, like some google-fonts, and the browser blocks it as unsecure resources inside a secure content. Google fonts can be loaded in https too.

How to reproduce:

- Just visit: https://padrinorb.com

Thanks!

**Comment by wikimatze** [comment]
Ji @jorgefuertes, I'm not quite sure, if GitHub offers SSL for their pages. Since their are only provide this for *.github.io pages (see the long thread under https://github.com/isaacs/github/issues/156) and we have a custom URL, this will not work.

**Comment by jorgefuertes** [comment]
Ok, ok, understood. We will wait until github provides full support for own certs or letsencrypt.

Thanks for your answer, @wikimatze.

**Comment by wikimatze** [comment]
That's fine. Would be nice if you could have an eye on this and inform us, when GitHub is ready for this step.

**Comment by jorgefuertes** [comment]
Ok, I'll try, anyway the hardcoded schema can be fixed to avoid browser warnings and let it load all the resources. The modern browsers uses SSL by default if available.

Those are just the google fonts, Lato and OpenSans.

**Comment by wikimatze** [comment]
I see, maybe I can fix the their load paths.
