### ISSUE TITLE
Consolidate "docs" and "source"

### ISSUE THREAD

**Issue by nesquena** [padrino/padrino-web-new#5]
we have the blog, guides, pages all here https://github.com/padrino/padrino-docs/tree/master what should we do with that in contrast to https://github.com/angeloashmore/padrino-web/tree/master/source? Should we merge all the content into the "docs" repo within the padrino-framework and have the site powered by that? or should we remove that directory from there?

**Comment by wikimatze** [comment]
Think we can keep at first the docs repo (https://github.com/angeloashmore/padrino-web/tree/master/source). When all the other stuff is finished we can move the content from the sub-repo into the main repo.

**Comment by nesquena** [comment]
Yeah, I think the goal is we want to merge all content into https://github.com/padrino/padrino-docs/tree/master and then we've loaded that as a submodule here: https://github.com/padrino/padrino-web-new

**Comment by nesquena** [comment]
This has been fixed now with the submodule containing all the content symlinked into the site.

**Comment by wikimatze** [comment]
Ok, created #10 to make it clear, how others can contribute to the page.

**Comment by nesquena** [comment]
Ok great idea, will definitely be a good addition to the site.
