### ISSUE TITLE
Merge Guides Content

### ISSUE THREAD

**Issue by nesquena** [padrino/padrino-web-new#7]
There are [guides here on padrino-docs](https://github.com/padrino/padrino-docs/tree/master/guides) and in the [source directory](https://github.com/angeloashmore/padrino-web/tree/master/source/guides) and then also the [latest ones pulled](https://github.com/padrino/temp-guides/tree/master) from the padrinorb.com. There are updates from the textile versions that will need to be pulled back into the markdown versions.

**Comment by wikimatze** [comment]
The first link is broken, what needs to be converted to which location? What is the temp-guides for (https://github.com/padrino/temp-guides/tree/master)? Thought we already ported all documents to the new location?

Bests Matthias

**Comment by nesquena** [comment]
Fixed the [first link](https://github.com/padrino/padrino-docs/tree/master/guides). [temp-guides](https://github.com/padrino/temp-guides/tree/master) is the latest content pulled directly from the padrino guides which started to deviate (with more recent updated content) from the markdown versions we had. Captured the final textile versions in [temp-guides](https://github.com/padrino/temp-guides/tree/master) since in certain cases, they had updates not captured anywhere else. However, in other cases, the docs versions had fixes not captured in the textile so it's a bit confusing to merge...

**Comment by wikimatze** [comment]
I understand and can work on that. So the final goal is to merge [temp-guides](https://github.com/padrino/temp-guides/tree/master) with the [first link](https://github.com/padrino/padrino-docs/tree/master/guides) and try to take the best of the two worlds. Think a separate branch will help with this. When this is done, the [temp-guides](https://github.com/padrino/temp-guides/tree/master) repo can be deleted, right?

Bests

Matthias

**Comment by nesquena** [comment]
Yep that's right! Your help on that would be amazing!

**Comment by wikimatze** [comment]
I'll work on that.

**Comment by wikimatze** [comment]
@nesquena can you delete the https://github.com/padrino/temp-guides repo? After that we can close this issue.

**Comment by nesquena** [comment]
Deleted. Thanks!

**Comment by wikimatze** [comment]
Awesome, now we can work on the other things!

**Comment by nesquena** [comment]
Yep! Thanks so much for your help. The site is really coming along nicely
